# Generated by Django 5.0.1 on 2024-01-20 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('emp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_nmbr', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_type', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_expiry', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_personal', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('net_payable_salary', models.FloatField(blank=True, null=True)),
                ('other_expense', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='emp_img',
            new_name='user_img',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emp_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='member_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='net_payable_salary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_expense',
        ),
        migrations.RemoveField(
            model_name='user',
            name='town',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zipcode',
        ),
    ]
