# Generated by Django 5.0.1 on 2024-01-21 17:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('vehicle_nmbr', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_type', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Company', 'Company')], max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phn_nmbr', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('odometer_reading', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Closed', 'Closed'), ('On Hold', 'On Hold'), ('In progress', 'In progress')], max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
