# Generated by Django 4.2.4 on 2024-02-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
